---
title: "Mapping deeper Gfish areas"
author: "Rachael Blake"
date: "October 28, 2015"
output: html_document
---

This is mapping trawl bottom depths between 151-300m from the RACE Trawl database.  
There is some info that species diversity changes with water depth.  
We're looking for some areas deeper than 150m to use for analysis.  

```{r , include=FALSE, echo=FALSE, results='hide'}
library(dplyr)
library(png)
library(grid)
library(rgdal)   
library(ggplot2)
library(maps)
library(mapdata)
library(mapproj)
```

Read in the map: 
```{r bare_map}
ak <- map_data('worldHires','USA:Alaska')

akmap <- ggplot() + geom_polygon(data=ak,aes(long,lat,group=group),fill=8,color="black") +
         theme(panel.background=element_rect(fill='aliceblue')) +
         xlab(expression(paste(Longitude^o,~'W'))) +
         ylab(expression(paste(Latitude^o,~'N'))) +
         coord_map(xlim = c(-165, -142),ylim = c(52, 61))

```

Read in the points data:
```{r trawl_points}
ALLD <- read.csv("./goaTrawl/Raw Trawl Data/goa_trawl_final_size_albers+temp.csv")

D_d <- ALLD %>%
       select(Lat,Lon,LonUTMAlbers,LatUTMAlbers,Station,Year,Stratum,BottomDepth) %>%
       filter(BottomDepth %in% c(151:300))

```

Make the plot: 
```{r plot, fig.height=8, fig.width=12}
AKgf_150_300 <- akmap +
                geom_point(data=D_d, aes(x=as.numeric(Lon), y=as.numeric(Lat)), size=3, shape=18, colour="blue")
AKgf_150_300

```

```{r}
D_dd <- ALLD %>%
        select(Lat,Lon,LonUTMAlbers,LatUTMAlbers,Station,Year,Stratum,BottomDepth) %>%
        filter(BottomDepth %in% c(301:600))
```

```{r , fig.height=8, fig.width=12}
AKgf_301_600 <- akmap +
                geom_point(data=D_dd, aes(x=as.numeric(Lon), y=as.numeric(Lat)), size=3, shape=18, colour="green")
AKgf_301_600

```

```{r}
D_dd <- ALLD %>%
        select(Lat,Lon,LonUTMAlbers,LatUTMAlbers,Station,Year,Stratum,BottomDepth) %>%
        filter(BottomDepth %in% c(151:250))

```

```{r, fig.height=8, fig.width=12}
AKgf_151_250 <- akmap +
                geom_point(data=D_dd, aes(x=as.numeric(Lon), y=as.numeric(Lat)), size=3, shape=18, colour="orange")
AKgf_151_250
```


```{r}
D_ddd <- ALLD %>%
        select(Lat,Lon,LonUTMAlbers,LatUTMAlbers,Station,Year,Stratum,BottomDepth) %>%
        mutate(DepthBin = ifelse((BottomDepth %in% c(0:100)), "0-100m",
                          ifelse((BottomDepth %in% c(101:200)),"101-200m",
                          ifelse((BottomDepth %in% c(201:300)),"201-300m",
                          ifelse((BottomDepth %in% c(301:400)),"301-400m",
                          ifelse((BottomDepth %in% c(401:500)),"401-500m",
                          ifelse((BottomDepth %in% c(501:600)),"500-600m","deep"))))))) %>%
        filter(DepthBin!="deep")
```

```{r, fig.height=8, fig.width=12}

AKgf_301_500 <- akmap +
                geom_point(data=D_ddd, aes(x=as.numeric(Lon), y=as.numeric(Lat),
                                           color=DepthBin), size=2, shape=18)
AKgf_301_500

```

