############################################
### PFX-Groundfish
### Calculate Rao's Q for Taxonomic Data
### Rachael Blake, March 2016
############################################

library(httr)
library(plyr)
library(dplyr)
library(XML)
library(curl)
library(rvest)
library(tidyr)
library(stringr)
library(vegan)
library(reshape2)
library(ggplot2)
library(scales)
library(ade4)
library(abind) 

# This sources the Rao's Q calculation with Jost correction from the paper
# Journal of Vegetation Science 21: 992–1000, 2010
# DOI: 10.1111/j.1654-1103.2010.01195.x
source("Appendix_Theseus/Appendix2/Rao.r")

# Use the species by CPUE per Area data generated by Ole's models.
URL_SPCPUEArea <- "https://drive.google.com/uc?export=download&id=0By1iaulIAI-udm1FT2trQUh5N1k"
SPCPUEArea_Get <- GET(URL_SPCPUEArea)
SPCPUEArea_1 <- content(SPCPUEArea_Get, as='text')
SPCPUEArea <- read.csv(file=textConnection(SPCPUEArea_1),stringsAsFactors=FALSE,head=TRUE)

SPCPUEArea <- dplyr::rename(SPCPUEArea, Year=year)
as.data.frame(SPCPUEArea)

# must make a 3D species by site array...x=species, y=area, z=year
b_arr <- array(NA, dim=c(11,57,30))  # makes an array of the correct size that's filled with NAs

c_arr <- acast(SPCPUEArea, Species~Year, value.var="Mean.totalDensity")


# The function requires that a species x site matrix is identified with "sample="
RaoJost<-Rao(sample=spxsite, dfunc=NULL, dphyl=NULL, weight=F, Jost=T, structure=NULL)

# The Rao function returns a list of lists of objects. 
names(RaoJost)

# For taxonomical diversity (identified as ‘TD’) different results are available.
names(RaoJost$TD)

# To extract the Alpha Simpson diversity for each plot:
RaoJost$TD$Alpha

# The ‘Pairwise_sample’ list includes all values of α, β and γ for each pairs of sample.
names(RaoJost$TD$Pairwise_sample)

# look at pairwise sample beta diversity 
RaoJost$TD$Pairwise_sample$Beta_prop 



 
 