---
title: "Figures for Blake et al. diversity paper"
author: "started by M. Hunsicker, revised by R.E. Blake"
date: "started 10/24/2016, revised 8/8/2017, revised 12/31/2018"
output:
  pdf_document: 
  fig_height: 4
  fig_width: 7
---

```{r, include=FALSE, echo=FALSE}
### This is what Mary Hunsicker did in Oct 2016.  
###Steps, R code and output files for generating diversity metrics for 10 shallow and 5 deep area in the GoA

#1. Selected deep areas by modifying Ole's original code.
#Code: git_repos/pfx-groundfish/goaTrawl/RScripts/SelectingDeepAreasForComparison.MH.R
#Output: pfx-groundfish/goaTrawl/Output Data/Deep_goa_discrete_areas_for_comparison_151_to_300m.final.csv

#2. Projected occurrence and density estimates to defined area by modifying Ole's orginal code to get mean CPUE and occurence for each area.
#Code: git_repos/pfx-groundfish/goaTrawl/RScripts/processINLAOutput_index_for_discrete.MH
#Output: git_repos/pfx-groundfish/All_sp_index_meanCPUEByArea.Shallow.MH.final.csv
#Output:  git_repos/pfx-groundfish/All_sp_index_occurrenceByArea.Shallow.MH.final.csv
#Output: git_repos/pfx-groundfish/All_sp_index_meanCPUEByArea.Deep.MH.final.csv
#Output: git_repos/pfx-groundfish/All_sp_index_occurrenceByArea.Deep.MH.final.csv

#3. Generated bootstrapped estimates of diversity metrics. 
#Code: git_repos/pfx-groundfish/goaTrawl/RScriptsBootstrap.Diversity.Final.R
#Output: git_repos/pfx-groundfish/DiversityMetrics.Shallow.Bootstrapped.Final
#Output: git_repos/pfx-groundfish/DiversityMetrics.Deep.Bootstrapped.Final

# 4. Generated figures using code in this r markdown file.

```


```{r, include=FALSE, echo=FALSE, results='hide'}
# Load all necessary packages
library(plyr) ; library(dplyr); library(tidyr) ; library(stringr) ; library(rgdal) ; 
library(sp) ; library(maptools) ; library(raster) ; library(ggplot2) ;  library(rgeos) ; 
library(maps) ; library(mapdata) ; library(mapproj) ; library(httr) ; library(extrafont) ; 
library(vegan) ; library(scales) ; library(gridExtra) ; library(RColorBrewer) ; 
library(GISTools) ; library(egg) ; library(marmap)

```

```{r loadMapData, message=FALSE, echo=FALSE, warning=FALSE}
# Map of area locations
# source("../diversity_scripts/Plotting_Exxon_Gfish_Areas.Rmd")
# seems like sourcing a Rmd used to work but doesn't now. 

# ak_areas_all

```

 
```{r map, cache=FALSE, echo=FALSE, warning=FALSE, include=FALSE}
# Figure 1: Map of shallow and deep study areas overlaid with EVOS slick 
#Map plotted in Lat Long:
ak <- fortify(maps::map('worldHires','USA:Alaska', plot=FALSE, fill=TRUE))

# get bathymetry
ak_bathy <- getNOAA.bathy(-165, -142, 54, 62, res=1, keep=TRUE)

akmap4 <- autoplot(ak_bathy, geom=c("raster", "contour"), coast=FALSE) +
          scale_fill_gradient2(low="deepskyblue4", mid="lightskyblue4", high="white", guide=FALSE) +
          geom_polygon(data=ak, aes(long,lat,group=group), fill=8, color="black") +
          xlab(expression(paste(Longitude^o,~'W'))) +
          ylab(expression(paste(Latitude^o,~'N'))) +
          coord_cartesian(xlim=c(-165, -142), ylim=c(54, 62))
  

```

```{r, include=FALSE, echo=FALSE}
# Shallow Study Areas
discrete_areas1 <- read.csv("../goaTrawl/Output Data/goa_discrete_areas_for_comparison(50_to_150m).csv")

discrete_areas1$area <- discrete_areas1$Area
discrete_areas1$Area <- factor(discrete_areas1$area)

# Re-naming discrete areas for Diversity paper
discrete_areas <- discrete_areas1 %>%
                  mutate(area = ifelse(area == "8", "NULL", 
                                ifelse(area == "9", "8", 
                                ifelse(area == "10", "9", 
                                ifelse(area == "11", "10", area))))) %>%
                  filter(area != "NULL") %>%
                  mutate(area = factor(area))

```

```{r, echo=FALSE}
discrete_areas$area1 <- factor(discrete_areas$area,
                               levels=c('1','2','3','4','5','6','7','8','9','10'))
# http://colorbrewer2.org/     brewer.pal(n=9, "PuRd")
pinks <- c("#FFE6DA", "#E3C9C6", "#FCC5C0", "#FA9FB5", "#F768A1",
           "#E7298A", "#DD3497", "#AE017E", "#7A0177",  "#49006A")     #E3C9C6   #FDE0DD
#blues <- c("#9ECAE1", "#6BAED6", "#4292C6", "#2171B5", "#084594")
#Colors1 <- c(pinks, blues)

ak_areas_all <- akmap4 +
                geom_point(data=discrete_areas, 
                           aes(LONGITUDE, LATITUDE, color=area1#,fill=area1
                               )) + 
                 scale_color_manual(values=pinks, name="Study Area", guide=FALSE) +
                # scale_fill_manual(values=pinks, name="Study Area", guide=FALSE) +
                 annotate("text", x=-146, y=59.9, label="1", size=4, fontface="bold") + 
                 annotate("text", x=-147.6, y=59.6, label="2", size=4, fontface="bold") +
                 annotate("text", x=-148.55, y=59.4, label="3", size=4, fontface="bold") +
                 annotate("text", x=-149.5, y=59.4, label="4", size=4, fontface="bold") +
                 annotate("text", x=-152.1, y=58.8, label="5", size=4, fontface="bold") +
                 annotate("text", x=-150.3, y=58.4, label="6", size=4, fontface="bold") +
                 annotate("text", x=-151.1, y=57.8, label="7", size=4, color="white", fontface="bold") +
                 annotate("text", x=-152.85, y=56.8, label="8", size=4, color="white", fontface="bold") +
                 annotate("text", x=-155.5, y=56.45, label="9", size=4, color="white", fontface="bold") +
                 annotate("text", x=-157.25, y=55.75, label="10", size=4, color="white", fontface="bold") +
                 annotate("segment", x=-156.25, y=54, xend=-156.25, yend=57.5, color="black", 
                          linetype="dashed", size=1) + 
                 annotate("segment", x=-149, y=58.8, xend=-149, yend=59.9, color="black", 
                          linetype="dashed", size=1) + 
                 annotate("segment", x=-149, y=58.95, xend=-142, yend=59.2, color="black", 
                          linetype="dashed", size=1) + 
                 annotate("segment", x=-149, y=58.8, xend=-151.25, yend=58.75, color="black", 
                          linetype="dashed", size=1) + 
                 annotate("segment", x=-151.25, y=58.75, xend=-151.25, yend=58.45, color="black", 
                          linetype="dashed", size=1) + 
                 annotate("segment", x=-151.25, y=58.45, xend=-153.35, yend=58.45, color="black", 
                          linetype="dashed", size=1) + 
                 annotate("segment", x=-153.35, y=58.45, xend=-153.35, yend=58.75, color="black", 
                          linetype="dashed", size=1) + 
                 annotate("text", x=-164, y=61.5, label="N", size=8, fontface="bold", color="black") + 
                 geom_segment(aes(x=-164,xend=-164,y=61.2,yend=61.8), size=1.5,
                              arrow=arrow(length = unit(0.5, "cm"))) +
                 annotate("text", x=-158, y=54.5, label="AP", fontface="bold", size=6) + 
                 annotate("text", x=-151, y=56.5, label="K", fontface="bold", size=6) + 
                 annotate("text", x=-152.5, y=59.5, label="CI", fontface="bold", size=6) + 
                 annotate("text", x=-144, y=59.5, label="PWS", fontface="bold", size=6) + 
                 theme(axis.text=element_text(size=15),
                       axis.title=element_text(size=15))
  
#ak_areas_all



```

```{r, eval=FALSE, echo=FALSE}
# test map for color bar for WSN talk
 # testmap <- akmap2 +
 #            geom_point(data=discrete_areas, 
 #                       aes(LONGITUDE, LATITUDE, color=as.numeric(as.character(area1)))) + 
 #            scale_color_gradientn(colours=pinks) +
 #            guides(colour=guide_colorbar(barheight = 20, barwidth = 5,label = FALSE,ticks = FALSE))
 # 
 # testmap
```


```{r, fig.cap="Locations of shallow areas (50-150 m) in Gulf of Alaska.",fig.pos="placehere",echo=FALSE,fig.height=4, fig.width=7}
#map of Shallow locations
#discrete_ShallowAreas$area <- discrete_ShallowAreas$Area
#discrete_ShallowAreas$Area <- factor(discrete_ShallowAreas$area)

#akmap + geom_point(data=discrete_ShallowAreas,aes(LONGITUDE,LATITUDE,color=Area))
```

```{r, include=FALSE, echo=FALSE, results='hide'}
# Make custom theme for plotting
theme_boxplot <- function(base_size = 12){
  theme_bw(base_size)%+replace%
    theme(legend.key.size=unit(15,"points"),
          legend.text=element_text(size=14),
          legend.key=element_blank(),
          legend.title=element_blank(),
          legend.background=element_rect(colour="white", fill="transparent"),
          plot.margin=unit(c(0.5,1,0.5,1), "lines"),
          panel.border=element_blank(),
          panel.spacing=unit(0,"lines"),
          panel.background=element_blank(),
          panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
          axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'),
          axis.ticks.length=unit(1,"mm"),
          axis.text.x = element_text(margin=margin(5,0,0,0), size=15),
          axis.text.y = element_text(margin=margin(0,5,0,0), size=15),
          axis.title.x=element_text(size=15, margin=margin(15,0,0,0)),
          axis.title.y=element_text(size=15, angle=90, margin=margin(0,15,0,0)),
          strip.text.x=element_text(size=14),
          strip.background=element_rect(colour="black", fill='white')
          )
}
```


```{r, include=FALSE, echo=FALSE,results='hide'}
# Figure 2a Diversity Metrics for 1 shallow areas
# Read in diversity metrics for 10 shallow areas (1-10)
shallowDat <- read.csv("../diversity-data/DiversityMetrics.Shallow.Bootstrapped.final.csv")
shallowDat$AREA <- as.factor(shallowDat$AREA)
```

```{r, include=FALSE, echo=FALSE,results='hide'}
#Boxplots Alpha Diversity Shallow Areas (exp H'):
sp_box1 <- ggplot(data=shallowDat, aes(AREA, y=Eff_Num_Sp)) + 
           geom_boxplot() + theme_boxplot() + 
           #xlab("Area (West <-> East)") +
           ylab("Alpha Diversity (exp H')") +
           xlim("10","9","8","7","6","5","4","3","2","1") + #shallow areas
           #  scale_fill_manual(values=barcolor) + ylim(0,0.5) +
           theme(legend.position="none", plot.background=element_blank(),
                 axis.text.x=element_text(size=15),
                 axis.title.x=element_blank(),
                 axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
                 axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'),
                 plot.title=element_text(colour="black", size=15,
                                         hjust=0.04, vjust=0.5, face="bold"))
```

```{r, echo=FALSE,fig.height=4, fig.width=7}
sp_box1
```

```{r, include=FALSE, echo=FALSE,results='hide'}
#Boxplots Beta Diversity Shallow Areas:
sp_box2 <- ggplot(data=shallowDat, aes(AREA, y=Exp_B_Div)) +
           geom_boxplot() + theme_boxplot() + 
         #  theme(axis.title.x=element_blank())+
           xlab("Area (West - East)") +
           ylab("Beta Diversity") +
           xlim("10","9","8","7","6","5","4","3","2","1") + #shallow areas
           #  scale_fill_manual(values=barcolor) + ylim(0,0.5) +
           theme(legend.position="none", plot.background=element_blank(),
                 axis.text.x=element_text(size=15),
                 axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
                 axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'),
                 plot.title=element_text(colour="black", size=15,
                                         hjust=0.04, vjust=0.5, face="bold"))
```

```{r, echo=FALSE,fig.height=4, fig.width=7}
sp_box2
```

```{r, include=FALSE, echo=FALSE,results='hide'}
#Boxplots Species Richness shallow areas:
sp_box3 <- ggplot(data=shallowDat, aes(AREA, y=Sp_rich)) + 
           geom_boxplot() + theme_boxplot() + #xlab("Area (West <-> East)") +
           ylab("Species Richness") +
           xlim("10","9","8","7","6","5","4","3","2","1") + 
           #  scale_fill_manual(values=barcolor) + ylim(0,0.5) +
           theme(legend.position="none", plot.background=element_blank(),
                 axis.text.x=element_text(size=15),
                 axis.title.x=element_blank(),
                 axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
                 axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'),
                 plot.title=element_text(colour="black", size=15,
                                         hjust=0.04, vjust=0.5, face="bold"))
```

```{r, fig.cap="Alpha diversity, beta diversity and species richness of the groundfish assemblage in shallow areas of the Gulf of Alaska. The medians and confidence intervals estimated from bootstrap sampling are shown.", echo=FALSE,fig.height=4, fig.width=7}
sp_box3
```

```{r}
source("../diversity_scripts/functional_diversity_metrics.R")

#shallow_FD  # This is the name of the shallow FD boxplot figure from Colette's script.

```



```{r, echo=FALSE}
sp_box123 <- ggarrange(sp_box1, sp_box3, sp_box2, shallow_FD, ncol=2, nrow=2)

```



######################################################################################################


```{r, include=FALSE, echo=FALSE, results='hide'}
# Figure 2b Diversity Metrics for deep areas
# Read in diversity data for 5 deep areas (11-15)
dat<-read.csv("../diversity-data/DiversityMetrics.Deep.Bootstrapped.final.csv")

deepDat <- dat%>%
           mutate(plotAREA = ifelse((AREA=="1"),'11',
                             ifelse((AREA=="2"),'12',
                             ifelse((AREA=="3"),'13',
                             ifelse((AREA=="4"),'14',       
                             ifelse((AREA=="5"),'15',
                             "")))))
                  )
deepDat$AREA<-as.factor(deepDat$plotAREA)
```

```{r, include=FALSE, echo=FALSE,results='hide'}
#Boxplots Alpha Diversity Deep Areas (exp H'):
sp_box4 <- ggplot(data=deepDat, aes(AREA, y=Eff_Num_Sp)) + 
           geom_boxplot() + theme_boxplot() + 
           #xlab("Area (West <-> East)") +
           theme(axis.title.x=element_blank())+
           ylab("Alpha Diversity (exp H')") +
           xlim("15","14","13","12","11") 
           #  scale_fill_manual(values=barcolor) + ylim(0,0.5) +
           theme(legend.position="none", plot.background=element_blank(),
                 axis.text.x=element_text(size=15),
                 plot.title=element_text(colour="black", size=15,
                                         hjust=0.04, vjust=0.5, face="bold"))
```

```{r, echo=FALSE,fig.height=4, fig.width=7}
sp_box4
```

```{r, include=FALSE, echo=FALSE,results='hide'}
#Boxplots Beta Diversity Deep Areas:
sp_box5 <- ggplot(data=deepDat, aes(AREA, y=Exp_B_Div)) + 
  geom_boxplot() + theme_boxplot() + 
  #xlab("Area (West <-> East)") +
  theme(axis.title.x=element_blank())+
  ylab("Beta Diversity") +
  xlim("15","14","13","12","11") 
  #  scale_fill_manual(values=barcolor) + ylim(0,0.5) +
  theme(legend.position="none", plot.background=element_blank(),
        axis.text.x=element_text(size=15),
        plot.title=element_text(colour="black", size=15,
                                hjust=0.04, vjust=0.5, face="bold"))
```

```{r, echo=FALSE,fig.height=4, fig.width=7}
sp_box5
```

```{r, include=FALSE, echo=FALSE,results='hide'}
#Boxplots Species Richness Deep areas:
sp_box6 <- ggplot(data=deepDat, aes(AREA, y=Sp_rich)) + 
  geom_boxplot() + theme_boxplot() + xlab("Area (West <-> East)") +
  ylab("Species Richness") +
  xlim("15","14","13","12","11") + 
  #  scale_fill_manual(values=barcolor) + ylim(0,0.5) +
  theme(legend.position="none", plot.background=element_blank(),
        axis.text.x=element_text(size=15),
        plot.title=element_text(colour="black", size=15,
                                hjust=0.04, vjust=0.5, face="bold"))
```

```{r, fig.cap="Alpha diversity, beta diversity and species richness of the groundfish assemblage in deep areas of the Gulf of Alaska. Medians and confidence intervals estimated from bootstrap sampling are shown.", echo=FALSE,fig.height=4, fig.width=7}
sp_box6
```