---
title: "Community Dissimilarities"
author: "Colette Ward"
date: "September 16, 2016"
output: html_document
---

```{r, include=FALSE, echo=FALSE, results='hide'}
# Load packages
library(vegan)
library(mvnormtest)
library(plyr)
library(dplyr)
library(tidyr)


```

```{r,  include=FALSE, echo=FALSE, results='hide'}
# load & prep look-up table of common names
common <- read.csv("./diversity-data/trawl_species_control_file.csv", header = T, stringsAsFactors = FALSE)

common1 <- common %>%
  select(database.name, common.name) %>%
  rename(Species = database.name)
for (i in 1:nrow(common1)) { # add common names for Sebastes 1 & 2
  if(common1$Species[i] == "Dusky.and.Dark.Rockfish") {common1$common.name[i] <- "Sebastes 1"}
  if(common1$Species[i] == "Rougheye.and.Blackspotted.Rockfish") {common1$common.name[i] <- "Sebastes 2"}
}
```


```{r,  include=FALSE, echo=FALSE, results='hide'}
# load mean annual CPUE data for Shallow Areas:
shallowCPUEArea <- read.csv("./diversity-data/All_sp_index_meanCPUEByArea.csv", header = T, stringsAsFactors = FALSE)

shallowCPUEArea2 <- left_join(shallowCPUEArea, common1, by = "Species") %>% # merge common names onto SPCPUEArea
  filter(area != "8") %>% # remove Ole's area 8
  mutate(area = revalue(area, c("9"="8", "10"="9", "11"="10")))


###########


# load mean annual CPUE for Deep areas:
deepCPUEArea <- read.csv("./diversity-data/All_sp_index_meanCPUEByArea.Deep.MH.final.csv", header = T, stringsAsFactors = FALSE) 

deepCPUEArea2 <- left_join(deepCPUEArea, common1, by = "Species") %>% # merge in common names
  mutate(area = revalue(area, c("1"="11", "2"="12", "3"="14", "4"="15", "5"="13")))

```


```{r,  include=FALSE, echo=FALSE, results='hide'}


# note: also use Simpson's dissimilarity, using occurrence data to get true turnover (independent of any species richness gradients)



# prep data for dissimilarity calcs
# need mean community composition matrix for each area (mean of 1984-2015)
shallowTemporalMeans <- shallowCPUEArea2 %>%
  select(common.name, Mean.totalDensity, area, year) %>%
  filter(area != "Total") %>%
  group_by(area, common.name) %>%
  summarize(temporal.mean = mean(Mean.totalDensity)) %>%
  ungroup() %>%
  spread(common.name, temporal.mean) %>% # make each species a column
  select(-area)
  # then spread as needed by vegan for dissimilarity matrix calcs: sites as rows, species as columns
View(shallowTemporalMeans)

#data(varespec)
#sptrans <- decostand(varespec, "max")
#apply(sptrans, 2, max)
#sptrans <- wisconsin(varespec)


shallow.dis.bray.wisc <- vegdist(wisconsin(shallowTemporalMeans), "bray"); shallow.dis.bray.wisc
shallow.dis.bray.hell <- vegdist(decostand(shallowTemporalMeans, "hell"), "bray"); shallow.dis.bray.hell

shallow.dis.jac <- vegdist(wisconsin(shallowTemporalMeans), "jaccard"); shallow.dis.jac
shallow.dis.jac.hell <- vegdist(decostand(shallowTemporalMeans, "hell"), "jaccard"); shallow.dis.jac.hell
    
# calculate community dissimilarities
# 1. pairwise between separate communities across space (plot dissimilarity vs distance)
# 2. then group adjacent sites (within x km) and repeat
# 3. then group at larger spatial scale (within x km) and repeat
# 4. plot bray-curtis temporal dissimilarity (at lag-1) vs spatial turnover

# pairwise between same community across years
shallowCPUEArea4 <- shallowCPUEArea2 %>%
  select(common.name, Mean.totalDensity, area, year) %>%
  filter(area != "Total") %>%
  spread(common.name, Mean.totalDensity) %>% # make each species a column
  mutate(area = as.numeric(area))
# now make a larger meta-region
View(shallowCPUEArea4)

for(i in 1:nrow(shallowCPUEArea4)) {
  if(shallowCPUEArea4$area[[i]] == c(1,2)) {shallowCPUEArea4$metaRegion1 <- 1} # note I should do this for each pair of adjacent sites (but only if distance is below a certain threshold?), ie (2,3), (3,4), (4,5), (5,6), ...
}
# == c() does not work
# right now all metaRegion1 = 1
  if(shallowCPUEArea4$area[[i]] %in% c(3,4)) {shallowCPUEArea4$metaRegion1 <- 2}
}
View(shallowCPUEArea4)
rm(shallowCPUEArea4)


# and then an even larger meta-region
# repeat
View(shallowCPUEArea4)

shallowCPUEArea_list <- split(shallowCPUEArea4, f = shallowCPUEArea4$metaRegion1)

for(i in seq_along(shallowCPUEArea_list)) {
  for(j in  .... shallowCPUEArea_list[[i]]$year) {
    # do dissimilarity matrix between each pair of adjacent years
    
  }
}



```