---
title: "Plotting Oil Spill"
author: "Rachael Blake"
date: "March 14, 2016"
output: html_document
---

```{r, include=FALSE, echo=FALSE, results='hide'}
library(plyr) ; library(dplyr); library(tidyr) ; library(stringr) ;library(rgdal) ; 
library(sp) ; library(maptools) ; library(raster) ; library(rgeos) ; library(ggplot2) ; 
library(maps) ; library(mapdata) ; library(mapproj) ; library(httr) ; library(scales) ;
library(RColorBrewer) ; library(GISTools)

```




Map plotted in Lat Long:

```{r, include=FALSE, echo=FALSE}
ak <- map_data('worldHires','USA:Alaska')

akmap2 <- ggplot() + 
          geom_polygon(data=ak, aes(long,lat,group=group), fill=8, 
                       color="black") +
          xlab(expression(paste(Longitude^o,~'W'))) +
          ylab(expression(paste(Latitude^o,~'N'))) +
          coord_map(xlim=c(-165, -142), ylim=c(54, 62)) +
          theme(panel.background=element_rect(fill='aliceblue')) 

```

```{r, include=FALSE, echo=FALSE}
# Shallow Study Areas
discrete_areas <- read.csv("../goaTrawl/Output Data/Shallow_goa_discrete_areas_for_comparison_Combined(50_to_150m).MH.csv")

discrete_areas$area <- discrete_areas$Area
discrete_areas$Area <- factor(discrete_areas$area)
```

```{r, include=FALSE, echo=FALSE}
# Deeper Study Areas
discrete_areas_deep <- read.csv("../goaTrawl/Output Data/Deep_goa_discrete_areas_for_comparison_150_to_300m.MH.csv")

discrete_areas_deep$Area <- factor(discrete_areas_deep$Area)
discrete_areas_deep <- rename(discrete_areas_deep, Depth=depth)

#discrete_areas_deep <- discrete_areas_deep[!duplicated(discrete_areas_deep[1:6]),]

```

```{r, echo=FALSE}
discrete_areas <- discrete_areas %>%
                  mutate(Area_Combo = ifelse((Area %in% c(1:7)), Area,
                                      ifelse((Area %in% c(10)), "8", "9")),
                         Depth_Cat = "Shallow")
                                    
discrete_areas_deep <- discrete_areas_deep %>%
                       mutate(Area_Combo = ifelse((Area %in% c(1)), "10",
                                           ifelse((Area %in% c(2)), "11",
                                           ifelse((Area %in% c(5)), "12",
                                           ifelse((Area %in% c(3)), "13", "14")))),
                              Depth_Cat = "Deep")

discrete_areas_combo <- bind_rows(discrete_areas, discrete_areas_deep)


```

```{r, echo=FALSE}
discrete_areas_combo$Area_Combo1 <- factor(discrete_areas_combo$Area_Combo,
                                           levels=c('1','2','3','4','5','6','7',
                                                    '8','9','10','11','12','13','14'))
# http://colorbrewer2.org/     brewer.pal(n=9, "PuRd")
pinks <- c("#FFE6DA", "#E3C9C6", "#FCC5C0", "#FA9FB5", "#F768A1",
           "#DD3497", "#AE017E", "#7A0177", "#49006A")    #E3C9C6     #FDE0DD
blues <- c("#9ECAE1", "#6BAED6", "#4292C6", "#2171B5", "#084594")
Colors1 <- c(pinks, blues)

ak_areas_all <- akmap2 +
                geom_point(data=discrete_areas_combo, 
                           aes(LONGITUDE, LATITUDE, color=Area_Combo1,
                               fill=Area_Combo1)) + 
                 scale_color_manual(values=Colors1, name="Study Area") +
                 scale_fill_manual(values=Colors1, name="Study Area") +
                 theme(legend.key.size=unit(11,"points"),
                       legend.text=element_text(size=9),
                       legend.key=element_rect(fill="white"),
                       legend.justification=c(1,0), 
                       legend.position=c(1,0)) +
                 guides(color=guide_legend(ncol=2))
ak_areas_all

```



Plotting Shoreline Surface Oil:

```{r, eval=FALSE, include=FALSE, echo=FALSE}
SOzipd <- tempfile()
download.file("http://pdx.axiomalaska.com/geoserver/wfs?service=WFS&version=1.0.0&request=GetFeature&outputFormat=SHAPE-ZIP&typeName=axiom:EVOSShorelineSurfaceOiling", SOzipd, mode="wb")
SOzip_Unz <- unzip(SOzipd, exdir="SOzipd")

slk_so <- readOGR(dsn="SOzipd",
                  layer="EVOSShorelineSurfaceOilingLine",
                  stringsAsFactors=FALSE)

crs(slk_so)
plot(slk_so, col='blue')

slk_so@data$id = rownames(slk_so@data)

LL_proj <-  "+proj=longlat +datum=NAD83"

slk_so <- spTransform(slk_so, LL_proj)

slk_so_pt <- fortify(slk_so, region="id")

slk_so_df <- join(slk_so_pt, slk_so@data, by="id")

slk_so_df <- slk_so_df[!is.na(slk_so_df$PosteriorO),]  # remove NA category
slk_so_df <- slk_so_df[!(slk_so_df$PosteriorO %in% c("UNOBSERVED")),]# remove "UNOBSERVED" category

```

```{r, eval=FALSE, include=FALSE, echo=FALSE}
# "LIGHT_IMPACT"  "VLIGHT_IMPACT" "MEDIUM_IMPACT" "HEAVY_IMPACT" 

slk_so_df$PosteriorO1 <- factor(slk_so_df$PosteriorO,
                                levels=c("VLIGHT_IMPACT","LIGHT_IMPACT",
                                         "MEDIUM_IMPACT","HEAVY_IMPACT"))
#This works, but it's only on the bare map.
ak_sobt <- akmap2 + 
           geom_point(data=slk_so_df, aes(x=long, y=lat, color=PosteriorO1), size=1) 
            
ak_sobt     

#Now this works also, but I don't like it.
ak_sot <- ak_areas_all + 
          geom_point(data=slk_so_df, aes(x=long, y=lat, size=PosteriorO1)) 
            
ak_sot           

```

```{r, echo=FALSE}

sho_shp <- readOGR(dsn="../Oil_Markdown_folder",
                   layer="all_0689_and_0889_surveys_merged",
                   stringsAsFactors=FALSE)

crs(sho_shp)
#plot(sho_shp, col='blue')

sho_shp@data$id = rownames(sho_shp@data)

LL_proj <-  "+proj=longlat +datum=NAD83"

sho_shp <- spTransform(sho_shp, LL_proj)

sho_shp_pt <- fortify(sho_shp, region="id")

sho_shp_df <- join(sho_shp_pt, sho_shp@data, by="id")

sho_shp_df <- sho_shp_df[!(sho_shp_df$OILING %in% c("UNOBSERVED", "NO_IMPACT")),]# remove "UNOBSERVED" and "NO_IMPACT" categories
#plot(sho_shp_df$long, sho_shp_df$lat)

```


```{r,  echo=FALSE}

sho_shp_df$OILING1 <- factor(sho_shp_df$OILING,
                             levels=c("VLIGHT_IMPACT","LIGHT_IMPACT",
                                      "MEDIUM_IMPACT","HEAVY_IMPACT"))

ak_so <- ak_areas_all + 
         geom_path(data=sho_shp_df, aes(x=long, y=lat, group=group, size=OILING1),
                                        color="#67001F") +
         scale_size_manual(values=c(0.5, 1.25, 2, 2.75), name="Shoreline Oiling",
                           breaks=c("VLIGHT_IMPACT","LIGHT_IMPACT",
                                     "MEDIUM_IMPACT","HEAVY_IMPACT"),
                           labels=c("Very Light", "Light", "Medium", "Heavy")) +
         geom_segment(aes(x=-162.9, y=61.35, xend=-164, yend=61.75), size=1,
                      arrow=arrow(length=unit(0.25, "cm"))) + 
         annotate("text", x=61, y=-162, label="N") 
            
ak_so           
          #    geom_text(aes(7, .9, label="correct color", color="NA*")) 
          #    annotate("text", x = 4, y = 25, label = "Some text")
```







DO NOT USE THE STUFF BELOW!

Plotting "Spill Effected Area":

```{r, eval=FALSE, include=FALSE, echo=FALSE}
SEAzipd <- tempfile()
download.file("http://pdx.axiomalaska.com/geoserver/wfs?service=WFS&version=1.0.0&request=GetFeature&outputFormat=SHAPE-ZIP&typeName=axiom:EVOSOilSpillExtent", SEAzipd, mode="wb")
SEAzip_Unz <- unzip(SEAzipd, exdir="SEAzipd")

spill_shp <- readOGR(dsn="SEAzipd",
                     layer="EVOSOilSpillExtentPolygon",
                     stringsAsFactors=FALSE)

spill_shp@data$id = rownames(spill_shp@data)

spill_shp@proj4string 

LL_proj <-  "+proj=longlat +datum=NAD83"

spill_shp <- spTransform(spill_shp, LL_proj)

spill_shp_pt <- fortify(spill_shp, region="id")

spill_shp_df <- join(spill_shp_pt, spill_shp@data, by="id")

```

```{r, eval=FALSE, include=FALSE, echo=FALSE}
akslk4 <- ak_areas_all +
          geom_polygon(data=spill_shp_df, aes(x=long, y=lat, group=id),
                       color='yellow', fill='yellow', size=0.25, alpha=0.4)
akslk4
#dev.off()
           
```



Plotting Shoreline Sub Surface Oil: 

```{r, eval=FALSE, include=FALSE, echo=FALSE}
SSOzipd <- tempfile()
download.file("http://pdx.axiomalaska.com/geoserver/wfs?service=WFS&version=1.0.0&request=GetFeature&outputFormat=SHAPE-ZIP&typeName=axiom:EVOSShorelineSubSurfaceOiling", SSOzipd, mode="wb")
SSOzip_Unz <- unzip(SSOzipd, exdir="SSOzipd")

slk_sss <- readOGR(dsn="SSOzipd",
                   layer="EVOSShorelineSubSurfaceOilingLine",
                   stringsAsFactors=FALSE)

crs(slk_sss)
plot(slk_sss, col='blue')

slk_sss@data$id = rownames(slk_sss@data)

LL_proj <-  "+proj=longlat +datum=NAD83"

slk_sss <- spTransform(slk_sss, LL_proj)

slk_sss_pt <- fortify(slk_sss, region="id")

slk_sss_df <- join(data.frame(slk_sss), slk_sss_pt, by="id")



```

```{r, eval=FALSE, include=FALSE, echo=FALSE}
ak_ssso <- ak_areas + 
           geom_point(data=slk_sss_df,aes(x=long,y=lat, group=as.factor(SegmentID)), 
                      size=3, color="black", fill="black") 
           
ak_ssso           


```











