---
title: "Plotting Oil Spill"
author: "Rachael Blake"
date: "March 14, 2016"
output: html_document
---

```{r, include=FALSE, echo=FALSE, results='hide'}
library(plyr) ; library(dplyr); library(tidyr) ; library(stringr) ;library(rgdal) ; 
library(sp) ; library(maptools) ; library(raster) ; library(rgeos) ; library(ggplot2) ; 
library(maps) ; library(mapdata) ; library(mapproj)

```

Map plotted in Albers projection (had to convert basemap and use other columns from discrete areas csv):

```{r BlankMap , include=FALSE, echo=FALSE}
ak <- map_data('worldHires','USA:Alaska')

# reproject AK map
aea_proj <-  "+proj=aea +lat_1=51 +lat_2=62 +lon_0=-150 +x_0=0 +y_0=0 +units=km +datum=WGS84"

ak_ll	<- ak[,1:2]
ak_sp	<- SpatialPoints(ak_ll, CRS("+proj=longlat +ellps=WGS84 +datum=WGS84"))
ak_sp_albers	<- spTransform(ak_sp, CRS(aea_proj))
ak_sp_alb_df	<- as(ak_sp_albers,"data.frame")
colnames(ak_sp_alb_df) <- c("LonUTMAlbers","LatUTMAlbers")
ak_alb <- cbind(ak,ak_sp_alb_df)

akmap <- ggplot() + geom_polygon(data=ak_alb,aes(LonUTMAlbers,LatUTMAlbers,group=group),
                                 fill=8,color="black") +
         theme(panel.background=element_rect(fill='aliceblue')) +
         xlab(expression(paste(Longitude^o,~'W'))) +
         ylab(expression(paste(Latitude^o,~'N'))) #+
       #  xlim = c(-1000, 500) + ylim = c(5500, 6250)
         # coord_map(xlim = c(-165, -142),ylim = c(52, 61))
      #   coord_map(xlim = c(-1000, 500),ylim = c(5500, 6250))
akmap
```


```{r DiscreteAreas, include=FALSE, echo=FALSE}
discrete_areas <- read.csv("../goaTrawl/Output Data/goa_discrete_areas_for_comparison(50_to_150m).csv")

# turn into spatial polygons object
# tell it what projection to use

discrete_areas$area <- discrete_areas$Area
discrete_areas$Area <- factor(discrete_areas$area)

sh_areas <- akmap + geom_point(data=discrete_areas,aes(LonUTMAlbers,LatUTMAlbers,color=Area))
sh_areas

```


```{r CorrectProjections, include=FALSE, echo=FALSE}
### Eventually make this download from online source!!
slk2_shp <- readOGR(dsn="../Oil_Markdown_folder", layer="ExxonSlick2", stringsAsFactors=FALSE)
crs(slk2_shp)
plot(slk2_shp, col='light blue', border='blue')

slk2_shp@data$id = rownames(slk2_shp@data)

slk2_shp@proj4string 

aea_proj <-  "+proj=aea +lat_1=51 +lat_2=62 +lon_0=-150 +x_0=0 +y_0=0 +units=km +datum=WGS84"

slk2_shp <- spTransform(slk2_shp, aea_proj)

slk2_shp_pt <- fortify(slk2_shp, region="id")

slk2_shp_df <- join(slk2_shp_pt, slk2_shp@data, by="id")


####

```


```{r, echo=FALSE}
akslk2 <- sh_areas + 
          geom_polygon(data=slk2_shp_df, aes(x=long, y=lat, group=id),
                       color='gray40', fill='blue', size=0.25)
akslk2



```


Map plotted in Lat Long (converted slick shapefile):

```{r, include=FALSE, echo=FALSE}
ak <- map_data('worldHires','USA:Alaska')

akmap2 <- ggplot() + geom_polygon(data=ak, aes(long,lat,group=group), fill=8, color="black") +
          xlab(expression(paste(Longitude^o,~'W'))) +
          ylab(expression(paste(Latitude^o,~'N'))) +
          coord_map(xlim=c(-165, -142), ylim=c(54, 62)) +
          theme(panel.background=element_rect(fill='aliceblue')) 
akmap2
```

```{r, include=FALSE, echo=FALSE}
discrete_areas <- read.csv("../goaTrawl/Output Data/goa_discrete_areas_for_comparison(50_to_150m).csv")

discrete_areas$area <- discrete_areas$Area
discrete_areas$Area <- factor(discrete_areas$area)

ak_areas <- akmap2 + 
            geom_point(data=discrete_areas,aes(LONGITUDE,LATITUDE,color=Area)) + 
            theme(legend.key=element_blank())
ak_areas
```

```{r, include=FALSE, echo=FALSE}
### Eventually make this download from online source!!
slk3_shp <- readOGR(dsn="../Oil_Markdown_folder", 
                    layer="ExxonSlick2", 
                    stringsAsFactors=FALSE)
crs(slk3_shp)
plot(slk3_shp, col='light blue', border='blue')

slk3_shp@data$id = rownames(slk3_shp@data)

slk3_shp@proj4string 

LL_proj <-  "+proj=longlat +datum=NAD83"

slk3_shp <- spTransform(slk3_shp, LL_proj)

slk3_shp_pt <- fortify(slk3_shp, region="id")

slk3_shp_df <- join(slk3_shp_pt, slk3_shp@data, by="id")

```

```{r, echo=FALSE}
akslk3 <- ak_areas + 
          geom_polygon(data=slk3_shp_df, aes(x=long, y=lat, group=id),
                       color='blue', fill='blue', size=0.25, alpha=0.4)

akslk3

```




Plotting Shoreline Sub Surface Oil: 

```{r, include=FALSE, echo=FALSE}
### Eventually make this download from online source!!
slk_sss <- readOGR(dsn="../Oil_Markdown_folder",
                   layer="EVOSShorelineSubSurfaceOilingLine",
                   stringsAsFactors=FALSE)
crs(slk_sss)
plot(slk_sss, col='blue')

slk_sss@data$id = rownames(slk_sss@data)

LL_proj <-  "+proj=longlat +datum=NAD83"

slk_sss <- spTransform(slk_sss, LL_proj)

slk_sss_pt <- fortify(slk_sss, region="id")

slk_sss_df <- join(data.frame(slk_sss), slk_sss_pt, by="id")


# slk_sss_pt <- do.call(rbind,lapply(slk_sss$SegmentID,
# function(x)data.frame(SegmentID=x,coordinates(slk_sss[slk_sss$SegmentID==x,]))))

```

```{r, include=FALSE, echo=FALSE}
ak_ssso <- akslk3 + 
           geom_path(data=slk_sss_df,aes(x=long,y=lat, color=SubSurface), size=3) 
           
ak_ssso           


```


Plotting Shoreline Surface Oil:

```{r, include=FALSE, echo=FALSE}
### Eventually make this download from online source!!
slk_so <- readOGR(dsn="../Oil_Markdown_folder",
                  layer="EVOSShorelineSurfaceOilingLine",
                  stringsAsFactors=FALSE)
crs(slk_so)
plot(slk_so, col='blue')

slk_so@data$id = rownames(slk_so@data)

LL_proj <-  "+proj=longlat +datum=NAD83"

slk_so <- spTransform(slk_so, LL_proj)

slk_so_pt <- fortify(slk_so, region="id")

slk_so_df <- join(slk_so_pt, slk_so@data, by="id")

```

```{r, include=FALSE, echo=FALSE}
ak_so <- ak_ssso + 
         geom_path(data=slk_so_df,aes(x=long,y=lat, group=PosteriorO), size=3) 
           
ak_so           

```



Plotting "Spill Effected Area":

```{r, include=FALSE, echo=FALSE}
spill_shp <- readOGR(dsn="../Oil_Markdown_folder", 
                     layer="EVOSOilSpillExtentPolygon", 
                     stringsAsFactors=FALSE)

spill_shp@data$id = rownames(spill_shp@data)

spill_shp@proj4string 

LL_proj <-  "+proj=longlat +datum=NAD83"

spill_shp <- spTransform(spill_shp, LL_proj)

spill_shp_pt <- fortify(spill_shp, region="id")

spill_shp_df <- join(spill_shp_pt, spill_shp@data, by="id")

```

```{r}
akslk4 <- akslk3 +
          geom_polygon(data=spill_shp_df, aes(x=long, y=lat, group=id),
                       color='yellow', fill='yellow', size=0.25, alpha=0.4)
akslk4
           
```







```{r, include=FALSE, echo=FALSE, results='hide'}

USA <- getData("GADM",country="USA",level=1)
plot(USA)
AK <- USA[USA$NAME_1=="Alaska",]
slk3_shp_test <- readOGR(dsn="./Oil_Markdown_folder", 
                    layer="ExxonSlick2", 
                    stringsAsFactors=FALSE)
plot(slk3_shp_test)
AK <- spTransform(AK,CRS(proj4string(slk3_shp)))
plot(AK,add=T,col='grey')
slk_sss_test <- readOGR(dsn="./Oil_Markdown_folder",
                   layer="EVOSShorelineSubSurfaceOilingLine",
                   stringsAsFactors=FALSE)
slk_sss_test <- spTransform(slk_sss,CRS(proj4string(slk3_shp)))

plot(slk_sss,add=T,lwd=3,col='blue')



```



